# Legacy v1 → v3 migration (HTTP 410 diagnosis)

Diagnosed 2026-07-31 on a server where `composio` (pip, 0.7.21) appeared configured but every command failed.

## Symptom

- `composio whoami` prints an API key (reads local config only — NOT a server validation).
- `composio connections` crashes with:
  `composio.exceptions.ApiKeyError: Unexpected error: HTTP 410`
  at `composio/client/__init__.py validate_api_key` → GET `{base}/v1/client/auth/client_info` with `x-api-key`.
- `composio login` fails with: `Error: {"error":"This endpoint is no longer available. Please upgrade to v3 APIs. "}`

## Root cause (verified, not assumed)

The 410 is **endpoint-wide**, not key-specific. Probe:

```bash
# All three return 410 — endpoint dead, key irrelevant:
curl -s -o /dev/null -w '%{http_code}' https://backend.composio.dev/api/v1/client/auth/client_info
curl -s -o /dev/null -w '%{http_code}' -H "x-api-key: ak_invalid123" https://backend.composio.dev/api/v1/client/auth/client_info
curl -s -o /dev/null -w '%{http_code}' -H "x-api-key: ak_CuW..." https://backend.composio.dev/api/v1/client/auth/client_info
```

- `https://backend.composio.dev/api/v3/client/auth/client_info` → 404 (v3 exists, different path layout).
- `https://api.composio.dev` → does not resolve (DNS). Do not chase it.
- `composio-core` on PyPI is frozen at **0.7.21** — `pip index versions composio-core` confirms; `pip install -U` is a no-op. There is NO pip upgrade path to the new CLI.

## Fix

Install the new-generation binary CLI (GitHub release, checksum-verified):

```bash
curl -fsSL https://composio.dev/install -o /tmp/composio_install.sh
# read it first: downloads composio-<os>-<arch>.zip from ComposioHQ/composio releases,
# installs to $HOME/.composio/composio, adds ~/.composio to PATH, verifies checksums.txt
bash /tmp/composio_install.sh --no-plugins   # or COMPOSIO_INSTALL_PLUGINS=0
```

- New binary: `~/.composio/composio`, reports `0.3.1` (June-July 2026 vintage).
- Old pip CLI binary may vanish from `~/.local/bin` after install — the installer owns `~/.composio`.
- `~/.composio/user_data.json` from the legacy CLI (`{"api_key": null}`) coexists harmlessly.

## New-CLI quirks discovered

- `composio login --no-wait --no-skill-install` prints `https://dashboard.composio.dev/?cliKey=<uuid>` + "Then run this command to complete login: composio login --poll". `--poll` uses the cached key, polls up to 10 min, exits once credentials are saved.
- Docs migrated: `docs.composio.dev/cli/*` → 404; `docs.composio.dev/docs/*` works (curl-able: cli, authentication, migration-guide). `docs.composio.dev/` redirects to `/docs`.
- Connect Link format (from docs): `https://connect.composio.dev/link/ln_abc123` — generated by `composio link <app>`; user authorizes in browser; tokens stored by Composio.

## Lesson

When a SaaS CLI's server endpoints all return 410 "upgrade to v3 APIs": distinguish key-revocation (401/403 or key-specific 410) from whole-backend decommission (410 with no/garbage key too). The latter means the installed client generation is obsolete — look for a new installer (often a compiled binary / GitHub release, not pip/npm), not a new key.
